In [4]:
import numpy as np
arr1 = np.arange(2,10)
arr1,arr1.dtype

(array([2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'))

In [2]:
arr1.astype(float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [3]:
arr1.astype(str)

array(['2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U21')

In [6]:
arr2 = np.array(["abc",10,20,(20,30)])
arr2

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [8]:
lst = ["abc",10,20,(20,30)]
arr2 = np.array(lst)
arr2

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [10]:
lst = [10,20,23.3,"float"]
arr2 = np.array(lst)          # squence is important int-float-string
arr2

array(['10', '20', '23.3', 'float'], dtype='<U32')

In [15]:
arr3 = np.arange(3,11).astype(float)
arr3

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
arr1 + arr3

array([ 5.,  7.,  9., 11., 13., 15., 17., 19.])

In [17]:
arr2.itemsize

128

In [18]:
arr1.size

8

In [19]:
arr1.ndim

1

In [20]:
arr3.itemsize

8

In [22]:
print(arr3.shape)

(8,)


In [26]:
import sys, numpy as np
sys.getsizeof(1.6)

24

In [27]:
sys.getsizeof([10,20,30])

88

In [29]:
sys.getsizeof("6")

42

In [42]:
sys.getsizeof("A")

42

In [32]:
sys.getsizeof({"name":"vikrant","address": "pune"})

184

In [44]:
# memory size of float - > 24
# memory size of int -> 28
# memory size of str -> single str element ->42

In [33]:
sys.getsizeof(1.6566666)

24

In [35]:
sys.getsizeof(7.8) * arr3.size   # 24 * 8 = 192


192

In [37]:
sys.getsizeof(46664)

28