In [4]:
import numpy as np
arr1 = np.arange(2,10)
arr1,arr1.dtype

(array([2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'))

In [2]:
arr1.astype(float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [3]:
arr1.astype(str)

array(['2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U21')

In [6]:
arr2 = np.array(["abc",10,20,(20,30)])
arr2

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [8]:
lst = ["abc",10,20,(20,30)]
arr2 = np.array(lst)
arr2

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [10]:
lst = [10,20,23.3,"float"]
arr2 = np.array(lst)          # squence is important int-float-string
arr2

array(['10', '20', '23.3', 'float'], dtype='<U32')

In [15]:
arr3 = np.arange(3,11).astype(float)
arr3

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
arr1 + arr3

array([ 5.,  7.,  9., 11., 13., 15., 17., 19.])

In [17]:
arr2.itemsize

128

In [18]:
arr1.size

8

In [19]:
arr1.ndim

1

In [20]:
arr3.itemsize

8

In [22]:
print(arr3.shape)

(8,)


In [26]:
import sys, numpy as np
sys.getsizeof(1.6)

24

In [27]:
sys.getsizeof([10,20,30])

88

In [29]:
sys.getsizeof("6")

42

In [42]:
sys.getsizeof("A")

42

In [32]:
sys.getsizeof({"name":"vikrant","address": "pune"})

184

In [44]:
# memory size of float - > 24
# memory size of int -> 28
# memory size of str -> single str element ->42

In [33]:
sys.getsizeof(1.6566666)

24

In [35]:
sys.getsizeof(7.8) * arr3.size   # 24 * 8 = 192


192

In [37]:
sys.getsizeof(46664)

28

In [46]:
print(np.random.rand(4,5))   # give value between 0 to 1 in row-4 col-5

[[0.23502366 0.21942646 0.30902776 0.48969935 0.728953  ]
 [0.23545    0.4028709  0.39873525 0.96453926 0.21151268]
 [0.06820866 0.38123064 0.40396149 0.03596307 0.74209602]
 [0.55151987 0.11482062 0.76792091 0.69240137 0.70113537]]


In [47]:
print(np.random.rand(3,3)) 

[[0.16981962 0.4301139  0.26316394]
 [0.85053293 0.68791313 0.61360707]
 [0.76392083 0.59040163 0.1413329 ]]


In [48]:
print(np.random.randint(10)) 

6


In [58]:
for i in range(5):
    arr = np.random.randint(14,100,size=(3,3))
    print(arr)

[[18 76 94]
 [80 80 77]
 [33 99 42]]
[[57 71 19]
 [64 40 92]
 [54 83 84]]
[[77 24 81]
 [99 25 15]
 [96 49 36]]
[[55 38 62]
 [56 81 21]
 [50 89 70]]
[[47 90 82]
 [47 29 83]
 [61 35 84]]


In [64]:
print(np.random.seed(6)) # to freeze we use seed to dont change values
arr = np.random.randint(14,100,size=(3,3))
print(arr)

None
[[24 87 98]
 [93 94 76]
 [39 15 89]]


In [63]:
for i in range(5):
    print(np.random.seed(6))
    arr = np.random.randint(14,100,size=(3,3))
    print(arr)
    print("__________________________________")

None
[[24 87 98]
 [93 94 76]
 [39 15 89]]
__________________________________
None
[[24 87 98]
 [93 94 76]
 [39 15 89]]
__________________________________
None
[[24 87 98]
 [93 94 76]
 [39 15 89]]
__________________________________
None
[[24 87 98]
 [93 94 76]
 [39 15 89]]
__________________________________
None
[[24 87 98]
 [93 94 76]
 [39 15 89]]
__________________________________


In [67]:
arr.mean(axis=1)   # 24+87+98=209/3=69.66  , 93+94+76=263/3=87.66 

array([69.66666667, 87.66666667, 47.66666667])

In [68]:
arr.mean(axis=0)  

array([52.        , 65.33333333, 87.66666667])

In [69]:
arr3 = np.random.randint(2,10,[4,6])
arr3

array([[7, 3, 4, 9, 3, 6],
       [8, 6, 3, 2, 4, 6],
       [6, 5, 9, 4, 7, 7],
       [4, 9, 3, 8, 4, 5]], dtype=int32)

In [71]:
arr3[1:3,3:5]

array([[2, 4],
       [4, 7]], dtype=int32)

In [72]:
arr3[2:3,2:3]

array([[9]], dtype=int32)

In [76]:
arr3[0::3,0::5]

array([[7, 6],
       [4, 5]], dtype=int32)

In [78]:
arr3[::-1,:]  # reversing last row as first row

array([[4, 9, 3, 8, 4, 5],
       [6, 5, 9, 4, 7, 7],
       [8, 6, 3, 2, 4, 6],
       [7, 3, 4, 9, 3, 6]], dtype=int32)

In [81]:
arr3[:,::-1]  # reversing last col as first col

array([[6, 3, 9, 4, 3, 7],
       [6, 4, 2, 3, 6, 8],
       [7, 7, 4, 9, 5, 6],
       [5, 4, 8, 3, 9, 4]], dtype=int32)

In [82]:
arr3[::-2,:]

array([[4, 9, 3, 8, 4, 5],
       [8, 6, 3, 2, 4, 6]], dtype=int32)

In [89]:
arr4 = np.random.randint(10,50,size=(4,6))
arr4

array([[22, 14, 43, 25, 15, 31],
       [16, 11, 19, 47, 23, 19],
       [11, 28, 12, 35, 31, 22],
       [14, 39, 24, 32, 13, 43]], dtype=int32)

In [90]:
arr4[arr4>15]

array([22, 43, 25, 31, 16, 19, 47, 23, 19, 28, 35, 31, 22, 39, 24, 32, 43],
      dtype=int32)

In [87]:
arr4 > arr   # size should be same

ValueError: operands could not be broadcast together with shapes (5,6) (3,3) 

In [92]:
arr3 < arr4

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [110]:
arr4

array([[ 99,  14, 300,  25,  15,  31],
       [ 16,  11,  19,  47,  23,  19],
       [ 11,  28,  12,  35,  31,  22],
       [ 14,  39,  24,  32,  13,  43]], dtype=int32)

In [112]:
arr4
a= arr4.flatten()
a[0]=100
print(arr4)
print("___________________________________")
print(a)

[[ 99  14 300  25  15  31]
 [ 16  11  19  47  23  19]
 [ 11  28  12  35  31  22]
 [ 14  39  24  32  13  43]]
___________________________________
[100  14 300  25  15  31  16  11  19  47  23  19  11  28  12  35  31  22
  14  39  24  32  13  43]


In [97]:
a[1]=200

In [113]:
arr4
a= arr4.ravel()
a[0]=2000
print(arr4)
print("___________________________________")
print(a)

[[2000   14  300   25   15   31]
 [  16   11   19   47   23   19]
 [  11   28   12   35   31   22]
 [  14   39   24   32   13   43]]
___________________________________
[2000   14  300   25   15   31   16   11   19   47   23   19   11   28
   12   35   31   22   14   39   24   32   13   43]
